# PRETRAINED_PATH = "complete/complex_detr/best.pth"
# PRETRAINED_PATH = "runs/FindPoints/0603_10-35-06__decoder/best.pth"
# PRETRAINED_PATH=""
PRETRAINED_PATH = "latest"
KEEP_EPOCH = True
EVAL = False
TEST = False
if EVAL:
    TEST = True
LEARNING_RATE = 1e-4
MAX_EPOCHS = 5000
EPOCHS = 5000
DATASET_SIZE = 100
DATASET_SIZE = None
BATCH_SIZE = 32
BATCH_STEP = 128 / BATCH_SIZE
DEVICE_IDS = [0]
DROPOUT = 0.1
